# Generated by Django 5.0.3 on 2024-04-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0004_rename_camada_curso_camada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='camada',
            new_name='promocion',
        ),
    ]
